name: Node.js CI

on:
    push:
        branches: ['hotfix/ci-cd']
    # pull_request:
    #     branches: ['master']

jobs:
    deploy-image:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Add .env file
              run: echo "${{ secrets.ENVIROMENT_VARIABLES }}" >> .env

            - name: Build & push Dockerfile image
              uses: mr-smithers-excellent/docker-build-push@v6
              with:
                  image: hdang09/housemate-fe
                  tags: v1, latest
                  registry: docker.io
                  dockerfile: Dockerfile
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

    pull-image:
        runs-on: self-hosted
        needs: deploy-image

        steps:
            - name: Stop and Remove the current container
              run: |
                  sudo docker stop housemate-fe || true
                  sudo docker rm housemate-fe || true
            - name: Pull the latest image
              run: sudo docker pull hdang09/housemate-fe
            - name: Start Docker image
              run: sudo docker run --name housemate-fe -d -p 3002:3000 hdang09/housemate-fe
